### ISSUE TITLE
Erreu NetUtils Ligne 133

### ISSUE THREAD

**Issue by arsium** [xaviermonin/ControlTower#1]
La séquence ne contient aucun élément c'est le message que j'ai lorsque j'utilise votre code

**Comment by xaviermonin** [comment]
Bonjour arsium,

L'application doit être lancée en administrateur et WinPCal ou LibPcap doit être installé.

**Comment by xaviermonin** [comment]
Il faut aussi une interface réseau avec l'ip v4 activé.
J'ai publié une mise à jour de l'application, tu peux réessayer avec la dernière version ?
